Update build-ksu.yaml

diff --git a/.github/workflows/build-ksu.yaml b/.github/workflows/build-ksu.yaml
--- a/.github/workflows/build-ksu.yaml
+++ b/.github/workflows/build-ksu.yaml
@@ -33,7 +33,7 @@ jobs:
       run: |
         mkdir -p kernel_src
         cd kernel_src
-        repo init -u https://android.googlesource.com/kernel/common -b android14-6.1-lts
+        repo init -u https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1
         repo sync -j$(nproc)
 
     - name: Setup KernelSU
@@ -43,12 +43,11 @@ jobs:
 
     - name: Apply SUSFS4KSU patches
       run: |
-        cp ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch $KERNEL_ROOT/KernelSU/
-        cp ./susfs4ksu/kernel_patches/50_add_susfs_in_kernel-android14-6.1.patch $KERNEL_ROOT/
-        cp ./susfs4ksu/kernel_patches/fs/susfs.c $KERNEL_ROOT/fs/
-        cp ./susfs4ksu/kernel_patches/include/linux/susfs.h $KERNEL_ROOT/include/linux/
-        cd $KERNEL_ROOT/KernelSU && patch -p1 < 10_enable_susfs_for_ksu.patch
-        cd $KERNEL_ROOT && patch -p1 < 50_add_susfs_in_kernel-android14-6.1.patch || echo "Check failed patches manually"
+        cd $KERNEL_ROOT
+        cp ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch KernelSU/
+        cp ./susfs4ksu/kernel_patches/50_add_susfs_in_kernel-android14-6.1.patch . 
+        patch -p1 < KernelSU/10_enable_susfs_for_ksu.patch
+        patch -p1 < 50_add_susfs_in_kernel-android14-6.1.patch || echo "Some patches failed. Check manually."
 
     - name: Enable KernelSU and SUSFS in config
       run: |
